spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:sqlserver://10.111.1.206:1433;databaseName=taipei_silver_generation
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: silverusr
    password: Tist24231451
    maximum-pool-size: 5
  jpa:
    generate-ddl: false
    show-sql: false
  mail:
    host: mail.systex.tw
    port: 25
    username: online
    password: KEqwp#5283ws
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    jpa:
      repositories:
        bootstrap-mode: lazy
tist:
  admin:
    debug: false
    mail-from: online@tist.com.tw
    upload: D:\upload
    system-url: http://localhost
debug: false