spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url:
    driver-class-name:
    username:
    password:
    maximum-pool-size: 10
  jpa:
    generate-ddl: true
    show-sql: true
    database-platform: 請輸入方言
  mail:
    host: casarray.systex.tw
    port: 25
    username: online
    password: KEqwp#5283ws
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    jpa:
      repositories:
        bootstrap-mode: lazy
tist:
  admin:
    debug: true
    mail-from: online@tist.com.tw
    upload: D:\upload
    system-url: http://localhost
debug: true